CREATE TABLE CONTATOS (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  sobrenome VARCHAR(100) NOT NULL,
  idade INT(11) NOT NULL,
  sexo VARCHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;